name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: "Install dependencies"
        id: install
        run: bun install --frozen-lockfile
      - name: "Check code formatting"
        if: steps.install.conclusion == 'success'
        run: bun run check:format
      - name: "Run linting"
        if: steps.install.conclusion == 'success'
        run: bun run check:lint
      - name: "Run type checking"
        if: steps.install.conclusion == 'success'
        run: bun run test:type
      - name: "Run tests"
        if: steps.install.conclusion == 'success'
        run: bun test
      - name: "Build"
        if: steps.install.conclusion == 'success'
        run: bun run build
      - name: "Run Documentation"
        if: steps.install.conclusion == 'success'
        run: bun run docs

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: "Install dependencies"
        run: bun install --frozen-lockfile
      - name: "Build"
        run: bun run build
      - name: "Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun run release
