name: 'Merge Dependencies'

# https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
on: [pull_request_target]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Extract information about the dependency
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.0
        with:
          github-token: ${{ secrets.GH_AUTOMERGE_TOKEN }}

      - name: Automatically merge the dependency
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_AUTOMERGE_TOKEN }}
