name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: corepack prepare pnpm@9 --activate
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22
      - name: 'Run tests on clean install'
        run: |
          pnpm install --frozen-lockfile
          pnpm test
